services:
  database:
    image: postgres
    container_name: postgres-database
    restart: always
    ports:
      - 2345:5432
    env_file:
      - .env
    networks:
      - app_network
    volumes:
      - pg:/var/lib/postgresql/data

  sorteio_app:
    container_name: sorteio_feliz_cont
    build: .
    ports:
      - 5000:5000
    env_file:
      - .env
    networks:
      - app_network
    depends_on:
      - database

volumes:
  pg:

networks:
  app_network:
    driver: bridge
